# from .train_valid_Cvpr_age_gender import Train_Cvpr_age_gender, Valid_Cvpr_age_gender

from .train_valid_Cvpr_age_gender_emotion import Train_Valid_Cvpr_age_gender_emotion, Valid_Cvpr_age_gender_emotion
from .train_valid_Age_gender import Valid_Cvpr_age_gender, Train_Cvpr_age_gender