from .MTL_ResNet_18_model import MTL_ResNet_18_model

from .MTL_ResNet_50_model import MTL_ResNet_50_model

from .agegenpredmodel import AgeGenPredModel


from .MTL_DenseNet_121_model import MTL_DenseNet_121_model

from .Elastic_MTL_DenseNet_121_model import Elastic_MTL_DenseNet_121_model